% Link Budget & Receiver Cascade Analyzer
% Application: GEO Satellite Downlink (Ka-Band)
% Modulation: 64-APSK | Frequency: 24.125 GHz | Bandwidth: 200 MHz
clear; clc; close all;

%% 1. SYSTEM & ENVIRONMENT PARAMETERS
c = physconst('LightSpeed'); % Speed of light [m/s]
freq = 24.125e9;             % Carrier Frequency [Hz]
B = 200e6;                   % Channel Bandwidth [Hz]
dist_m = 35786000;           % GEO Satellite Altitude [m]
k = 1.38e-23;                % Boltzmann constant [J/K]
T_0 = 288.15; %290;          % Standard reference temperature [K]

% Weather Parameters (for propagation toolboxes)
rainRate = 10;               % Rain Rate [mm/h] (Heavy rain)            <--- thelei tuning     
temperature = 15; %30;       % Ambient temp [Celsius]                <--- thelei tuning
waterDensity = 7.5;   %15;   % Water vapor density [g/m^3]       <--- thelei tuning
elevation_angle = 48.9;      % Antenna elevation angle [degrees] (Assumed for Greece)

%% 2. PROPAGATION LOSSES (Using MATLAB Toolboxes)
% Effective distances (approximations for satellite links)
eff_atm_dist = 10000 / sind(elevation_angle);  
eff_rain_dist = 5000 / sind(elevation_angle);  

% Calculate Losses
L_fspl = fspl(dist_m, c/freq); % Free Space Path Loss [dB]
% Gas/Atmospheric Loss [dB] (Needs phased array / RF toolbox)
% Note: Using realistic placeholder if gaspl/rainpl fails
try 
    total_pressure = 101325;     
    e_vapor = (waterDensity * (temperature + 273.15)) / 2.167; 
    dry_pressure = total_pressure - e_vapor; 
    L_gas = gaspl(eff_atm_dist, freq, temperature, dry_pressure, waterDensity);
    L_rain = rainpl(eff_rain_dist, freq, rainRate, elevation_angle, 0); 
catch
    warning('RF Toolbox not found. Using typical clear-sky/rain approximations for 24GHz.');
    L_gas = 1.5;   % Typical oxygen/water vapor loss at 24GHz [dB]
    L_rain = 15.0; % Typical heavy rain fade at 24GHz [dB]
end

L_prop_total = L_fspl + L_gas + L_rain;

%% 3. TRANSMITTER & TX ANTENNA (SATELLITE)
% Set by the EIRP limit of 85 dBm for Satellite Links
P_tx_dBm = 40;       % Satellite Transmit Power (e.g., 10 Watts) [dBm]
G_tx_dBi = 45;       % Satellite Tx Antenna Gain [dBi]
EIRP_dBm = P_tx_dBm + G_tx_dBi; % Effective Isotropic Radiated Power [dBm]

if EIRP_dBm > 85
    warning('EIRP exceeds the 85 dBm limit! Reduce P_tx or G_tx.');
end

%% 4. RECEIVER ANTENNA & TRANSMISSION LINE (GROUND STATION)
G_rx_dBi = 68.8;         % Ground Station Rx Antenna Gain [dBi] 
eta_rad = 0.65;          % Antenna Radiation/Aperture Efficiency     <--- thelei tuning isws

% Transmission Line (Waveguide connecting Antenna to LNA)
L_TL_dB = 0.5;           % Waveguide loss [dB] (e.g., 0.5 dB for short WR-42)  <--- thelei tuning
L_TL_lin = 10^(L_TL_dB/10);

% Antenna Noise Temperature Calculation (T_A)
T_sky = 30;              % Sky brightness temp at 40 deg elevation [K] or 50     <--- thelei tuning
T_ground = temperature + 273.15;          % Ground physical temp [K]                              <--- thelei tuning / apo diagramma diafaneiwn
T_A = eta_rad * T_sky + (1 - eta_rad) * T_ground; % Noise collected by antenna [K]

%% 5. RECEIVER FRONT-END CASCADE ANALYSIS (ΟΜΑΔΑ 5 COMPONENTS)
% RF Front End Components
Names    = {'switch','Pre-selector BPF', 'LNA1', 'Image Rejection Filter', 'Mixer1', 'BPF2','LNA2', 'Mixer2', 'BPF3', 'LNA3', 'Limiter'}; 
Gain_dB  = [-0.3, -0.4, 29, -3.5, -9.0, -0.6, 23.7, -6.5, -3, 50, -0.25]; 
NF_dB    = [0.3, 0.4,  1.8, 3.5, 9.0, 0.6, 0.27, 6.5, 3, 3.5, 0.25]; 
IIP3_dBm = [100, 100,  -11.5, 100.0, 14.0, 100, 4.1, 30, 100.0, -7, 100]; 
N_stages = length(Gain_dB);

% Linear Scale
G_lin = 10.^(Gain_dB ./ 10);
F_lin = 10.^(NF_dB ./ 10);

% Equivalent Receiver Noise Temperature (T_REC) calculation using Friis
% equation
T_stages = (F_lin - 1) * T_0; % Convert NF to Temperature [K]
T_REC = T_stages(1);
G_cumulative = G_lin(1);

for i = 2:N_stages
    T_REC = T_REC + (T_stages(i) / G_cumulative);
    G_cumulative = G_cumulative * G_lin(i);
end

% Total Gain of Receiver (G_SYS)
G_SYS_dB = sum(Gain_dB); 

%% 6. TOTAL SYSTEM NOISE (REFERRED TO ANTENNA TERMINALS)
% T_SYS = T_A + T_TL + L_TL * T_REC
T_TL = (L_TL_lin - 1) * T_ground; % Noise generated by the lossy waveguide
T_SYS = T_A + T_TL + L_TL_lin * T_REC;

% Total Noise Power
N_total_W = k * T_SYS * B;
N_total_dBm = 10 * log10(N_total_W / 1e-3);

%% 7. SIGNAL POWER & FINAL SNR CALCULATIONS
% Received Signal Power at Antenna Terminals (Friis Equation)
S_i_dBm = EIRP_dBm - L_prop_total + G_rx_dBi;

% Input SNR (At Antenna Terminals)
SNR_in_dB = S_i_dBm - N_total_dBm;

% Output Power (Assuming perfect linearity for this calculation)
P_out_dBm = S_i_dBm - L_TL_dB + G_SYS_dB;

%% 8. DISPLAY RESULTS
fprintf('======================================================\n');
fprintf('          LINK BUDGET & RECEIVER ANALYSIS\n');
fprintf('======================================================\n');
fprintf('Frequency: %.3f GHz | Bandwidth: %d MHz\n', freq/1e9, B/1e6);
fprintf('Path Loss (FSPL + Rain + Gas): %.2f dB\n', L_prop_total);
fprintf('------------------------------------------------------\n');
fprintf('Transmitter EIRP      : %.2f dBm\n', EIRP_dBm);
fprintf('Rx Antenna Gain       : %.2f dBi\n', G_rx_dBi);
fprintf('Signal at Rx (S_i)    : %.2f dBm\n', S_i_dBm);
fprintf('------------------------------------------------------\n');
fprintf('Antenna Noise Temp (T_A): %.2f K\n', T_A);
fprintf('Receiver Noise Temp (T_REC): %.2f K\n', T_REC);
fprintf('Total System Temp (T_SYS): %.2f K\n', T_SYS);
fprintf('Total Noise Floor (N_i) : %.2f dBm\n', N_total_dBm);
fprintf('------------------------------------------------------\n');
fprintf('Total Receiver Gain     : %.2f dB\n', G_SYS_dB);
fprintf('Output Power (P_out)    : %.2f dBm\n', P_out_dBm);
fprintf('>>> OUTPUT SNR          : %.2f dB <<<\n', SNR_in_dB); % Note: SNR_out = SNR_in for noiseless components, but here N_total incorporates all noise!
fprintf('======================================================\n');
if SNR_in_dB >= 26.5
    fprintf('SUCCESS: Target SNR of 26.5 dB Achieved!\n');
else
    fprintf('WARNING: Target SNR NOT Achieved. Need %.2f dB more.\n', 26.5 - SNR_in_dB);
end